### ISSUE TITLE
Support copyright patterns, not just exact matches

### ISSUE THREAD

**Issue by gdaolewe** [Stuk/eslint-plugin-header#2]
Given the following .eslintrc:

``` json
{
    "plugins": [
        "header"
    ],
    "rules": {
        "header/header": [2, "block", "Copyright 2016"]
    }
}
```

If a file has exactly the comment:
`/*Copyright 2016*/`
it will pass linting, but if the first comment is instead:
`/* Copyright 2016 */` (not the whitespace) it will fail. I'd like the ability to specify a string pattern or regular expression for headers to be matched against.

**Comment by ctavan** [comment]
@gdaolewe I've implemented this in #4, maybe you want to give it a try?
