### ISSUE TITLE
Feature request - Adding newline(s) after header

### ISSUE THREAD

**Issue by opera-emoller** [Stuk/eslint-plugin-header#28]
Thanks for a neat project, we started using this in a new project a few weeks ago and just like @maksnester requested in one of the issue threads we'd like to have a newline after our header. I made a PR.

**Comment by DLehenbauer** [comment]
(FYI - I was just looking for this feature.)

**Comment by opera-emoller** [comment]
@DLehenbauer https://www.npmjs.com/package/patch-package seems to be essential if you want to be on the bleeding edge of things :)
