### ISSUE TITLE
different copyrights for different path

### ISSUE THREAD

**Issue by akosyakov** [Stuk/eslint-plugin-header#44]
I have a repo in which different files should have different copyrights. Such files are separated by different folders. Is there a way to configure different copyrights for different relative paths?

**Comment by Stuk** [comment]
Like any rule, you should be able to add a `.eslintrc` file in the subdirectory to override the parent configuration: https://eslint.org/docs/user-guide/configuring/configuration-files#cascading-and-hierarchy

Having said this I have not tried it with this package.
